name: QuickStartSwiftUI

attributes:
  LastSwiftUpdateCheck: '1420'
  LastUpgradeCheck: '1250'

options:
  defaultConfig: Debug
  groupSortPosition: bottom
  transitivelyLinkDependencies: false

packages:
  SendbirdChatSDK:
    url: https://github.com/sendbird/sendbird-chat-sdk-ios
    from: 4.21.1
    
schemes:
  QuickStartSwiftUI:
    analyze:
      config: Debug
    archive:
      config: Release
    build:
      targets:
        QuickStartSwiftUI:
        - running
        - testing
        - profiling
        - analyzing
        - archiving
    profile:
      config: Debug
    run:
      config: Debug

settingGroups:
  preset_generic:
    CODE_SIGN_STYLE: Automatic
    CURRENT_PROJECT_VERSION: '1'
    DEVELOPMENT_TEAM: RM4A5PXTUX
    FRAMEWORK_SEARCH_PATHS: ''
    IPHONEOS_DEPLOYMENT_TARGET: '15.0'
    LD_RUNPATH_SEARCH_PATHS: ["$(inherited)", "@executable_path/Frameworks", "@loader_path/Frameworks"]
    MARKETING_VERSION: '1.0.0-beta.2'
    PRODUCT_NAME: "$(TARGET_NAME)"
    SDKROOT: iphoneos
    SWIFT_VERSION: '5.0'
    VERSION_INFO_PREFIX: ''
    VERSIONING_SYSTEM: apple-generic
  preset_all:
    groups:
      - preset_generic

targets:
 QuickStartSwiftUI:
    dependencies:
    - target: NotificationService
    - package: SendbirdChatSDK
    - sdk: UserNotifications.framework
    platform: iOS
    productName: QuickStartSwiftUI
    settings:
      groups:
        - preset_all
      base:
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        INFOPLIST_FILE: QuickStartSwiftUI/Assets/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.sendbird.swiftui.sample
        CODE_SIGN_ENTITLEMENTS: QuickStartSwiftUI/Assets/QuickStartSwiftUI.entitlements
        CODE_SIGN_IDENTITY: "Apple Development"
        SWIFT_ACTIVE_COMPILATION_CONDITIONS:
          - "$(inherited)"
          - SWIFTUI
    sources:
    - path: QuickStartSwiftUI
    - path: ../Sources/
      excludes:
        - Info.plist
    type: application
 NotificationService:
    platform: iOS
    productName: NotificationService
    settings:
      groups:
        - preset_all
      base:
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        IPHONEOS_DEPLOYMENT_TARGET: '15.0'
        GENERATE_INFOPLIST_FILE: true
        INFOPLIST_FILE: NotificationService/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.sendbird.swiftui.sample.SwiftUINotificationService
        CODE_SIGN_ENTITLEMENTS: NotificationService/SwiftUINotificationService.entitlements
        CLANG_WARN_QUOTED_INCLUDE_IN_FRAMEWORK_HEADER: 'YES'
    sources:
    - path: NotificationService
    type: app-extension
